### PR TITLE
Naming guidelines for protected and static fields

### PR DESCRIPTION
**Pull request by maxbrodin**
It seems our naming guidelines do not include rules for the following access modifiers:

```
private static
protected
protected internal
protected static
```

We've already described naming conventions for private fields, imho it's a must that we have rules for all of possible modifiers

### CODE REVIEW

**Comment by maxbrodin** [comment]
@akoshelev Nice point, fixed spec and added example file.

**Comment by akoshelev** [comment]
I'd prefer to see this `sample.cs` file inlined to naming conventions document. @eugene-kartsev what do you think?

**Comment by eugene-kartsev** [comment]
I'd prefer as little cross-links as possible. So yes, in-lining this document seems better.

**Comment by akoshelev** [comment]
lgtm

**Pull request merged**
